### ISSUE TITLE
Add Code of Conduct.md 

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [adarsh-singh01/PrithWe#1]
Hey @adarsh-singh01  ,
It is important for our community to have a clear and concise code of conduct to ensure a welcoming and inclusive environment for all contributors. A Code of Conduct sets the expectation for behavior and outlines the steps for reporting and addressing unacceptable behavior. This can greatly enhance the community experience and maintain a respectful and collaborative atmosphere.
I want to add Code_of_conduct.md, please assign me this issue.

**Comment by adarsh-singh01** [comment]
> Hey @adarsh-singh01  ,
> It is important for our community to have a clear and concise code of conduct to ensure a welcoming and inclusive environment for all contributors. A Code of Conduct sets the expectation for behavior and outlines the steps for reporting and addressing unacceptable behavior. This can greatly enhance the community experience and maintain a respectful and collaborative atmosphere.
> I want to add Code_of_conduct.md, please assign me this issue.

Hey , Are you doing this.. ?

**Comment by Santhosh-Siddhardha** [comment]
Raised PR, Please assign gssoc and level badges to this PR and my previous PR
