### ISSUE TITLE
[Feature]: Implement "Back to Top" Button and Enhance "Why Choose Us" Section with Attractive CSS Cards

### ISSUE THREAD

**Issue by AnkitLuhar** [adarsh-singh01/PrithWe#103]
**Is your feature request related to a problem? Please describe.**

Users often find it inconvenient to manually scroll back to the top of a webpage, especially on long pages with extensive content. Additionally, the current design of the "Why Choose Us" section lacks visual appeal and may not effectively capture the attention of users.

**Describe it in detail.**
The feature request involves addressing two aspects:

1>Adding a "Back to Top" button to enable users to quickly navigate back to the top of the page with a single click, enhancing overall usability and efficiency.

2>Improving the visual presentation of the "Why Choose Us" section by applying better and more attractive CSS styles to the cards within this section, making it more visually appealing and engaging for users.

**Describe the solution you'd like.**

1>"Back to Top" Button: Implement a fixed-position button at the bottom-right corner of the webpage, clearly labeled "Back to Top". When clicked, it should smoothly scroll the page back to the top, providing a seamless user experience.

2>Enhanced CSS Cards: Style the cards within the "Why Choose Us" section using modern CSS techniques, including subtle animations, gradients, shadows, and other decorative elements to make the cards stand out and capture the user's attention.

**Additional context:**

Implementing a "Back to Top" button and enhancing the visual presentation of the "Why Choose Us" section will collectively improve user experience, making navigation more convenient and content more engaging.

Screenshot:

![Screenshot (556)](https://github.com/adarsh-singh01/PrithWe/assets/142730608/73138eb1-79eb-4d11-a2d1-51b75da946ea)
![Screenshot (557)](https://github.com/adarsh-singh01/PrithWe/assets/142730608/950e195f-11dd-4c2f-b071-bf845729cc95)

**Assign me these task under the Gssoc'24 .**

**Comment by AnkitLuhar** [comment]
@adarsh-singh01, I am seeking to contribute to your project and would like to be assigned this issue.

**Comment by adarsh-singh01** [comment]
Assigned!

**Comment by adarsh-singh01** [comment]
Can you please give a star to this repo?

**Comment by AnkitLuhar** [comment]
Hello @adarsh-singh01, I'm facing an issue while pushing the code. Could you please guide me on how to resolve this error? When I try to execute the command git push origin other, I encounter the following message:
remote: Permission to adarsh-singh01/PrithWe.git denied to AnkitLuhar.
fatal: unable to access 'https://github.com/adarsh-singh01/PrithWe.git/': The requested URL returned error: 403

**Comment by adarsh-singh01** [comment]
Hey Ankit, I will look into this error tomorrow after 1pm...
I have an exam tomorrow.

**Comment by AnkitLuhar** [comment]
Ohk,it's fine!

**Comment by adarsh-singh01** [comment]
> Hello @adarsh-singh01, I'm facing an issue while pushing the code. Could you please guide me on how to resolve this error? When I try to execute the command git push origin other, I encounter the following message:
> remote: Permission to adarsh-singh01/PrithWe.git denied to AnkitLuhar.
> fatal: unable to access 'https://github.com/adarsh-singh01/PrithWe.git/': The requested URL returned error: 403
> 

You are trying to push in which repo?... The original or the one you have forked? ... 

See this video as of now: https://youtu.be/8lGpZkjnkt4?si=Wt6EUBD_wOM0Z7HN

Will guide you Tomorrow if the video doesn't help.

**Comment by AnkitLuhar** [comment]
Trying to push on fork repo, firstly I push the code in master branch then,it shows there is nothing to compare or there is no historical matches are found,so then I create one more branche name as "other". When I going to push the code then the error is occurs

**Comment by adarsh-singh01** [comment]
Hey Ankit , i think you should again fork the repo then clone it and make your changes...error might be coming from branch conflicts as PRs are coming on daily basis and when i merge them your repo code is behind.

**Comment by AnkitLuhar** [comment]
Ohk let me try...

**Comment by AnkitLuhar** [comment]
code is succesfully push on the main branch but,it shows the error due to which i can't open pull request : adarsh-singh01:main and AnkitLuhar:main are entirely different commit histories.

**Comment by AnkitLuhar** [comment]
@adarsh-singh01 waiting for your response ,regarding the conflicts during the pull request

**Comment by adarsh-singh01** [comment]
Refer this once : https://stackoverflow.com/questions/67318083/main-and-master-are-entirely-different-commit-histories-i-am-adding-a-new-repos

**Comment by AnkitLuhar** [comment]
Hey, @adarsh-singh01 , thanks for waiting. I have successfully opened the pull request and am eager to contribute to more of your projects. If there are any opportunities available, please let me know.
