### ISSUE TITLE
Updating CSS of History page

### ISSUE THREAD

**Issue by asthanegi14** [adarsh-singh01/PrithWe#104]
On small devices, the text on the current webpage is extending outside of the box. I want to make this table scrollable from the right side to the left within the box.

![Screenshot (987)](https://github.com/adarsh-singh01/PrithWe/assets/93486108/78fc0f78-d70d-4c34-8e5c-61dff309c618)

**Comment by adarsh-singh01** [comment]
#116 it is already assigned
