### ISSUE TITLE
Navbar is not sticky

### ISSUE THREAD

**Issue by the-code-artist** [adarsh-singh01/PrithWe#106]
Navbar is not sticky and the user might face difficulty in navigating to other pages through while he is in the middle of some other page
![image](https://github.com/adarsh-singh01/PrithWe/assets/115625321/0a7f32c3-de4a-4958-9eb7-cf41a6b42b54)
as demonstrated above in order to navigate to other pages I need to move to top of the page 
whereas a sticky navbar can help in easy switching between different pages

**Comment by the-code-artist** [comment]
Hey @adarsh-singh01
I am excited in resolving this issue and contribute it to the project.
please do assign me this issue under GSSOC'24 !!

**Comment by adarsh-singh01** [comment]
One more contributor was assigned this issue but his PR was causing many UI problems in the site.like padding from top of all pages , some elements were going above the navbar..

**Comment by the-code-artist** [comment]
I can fix that!!
please do assign me this issue under GSSOC'24!
