### ISSUE TITLE
Add some animations in landing page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [adarsh-singh01/PrithWe#108]
we can add some animations in landing page and other pages using AOS.js,ityped js etc

**Comment by adarsh-singh01** [comment]
send a short video of sample or proposed idea

**Comment by RamakrushnaBiswal** [comment]
https://ramakrushnabiswal.github.io/landing-website-connifyz/

@adarsh-singh01

**Comment by adarsh-singh01** [comment]
@RamakrushnaBiswal you can work on it but if it doesn't look good it might not be merged

**Comment by RamakrushnaBiswal** [comment]
@adarsh-singh01 review the PR

**Comment by RamakrushnaBiswal** [comment]
@adarsh-singh01 

https://github.com/adarsh-singh01/PrithWe/assets/125277258/a15f406e-7347-43ea-93b0-d49e313e2306
