### ISSUE TITLE
[Feat]: Auto Commenting Feat for Issue Creation 

### ISSUE THREAD

**Issue by Asymtode712** [adarsh-singh01/PrithWe#11]
This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

![issue creation](https://github.com/adarsh-singh01/PrithWe/assets/115717746/68102138-5190-4f35-a72e-1e2707ddc280)

**Comment by Asymtode712** [comment]
@adarsh-singh01 please assign me this issue under gssoc

**Comment by adarsh-singh01** [comment]
Can you please give a star to this repository

**Comment by Asymtode712** [comment]
@adarsh-singh01 Done
