### ISSUE TITLE
Fix in UI of User Details (Admin Panel)

### ISSUE THREAD

**Issue by PratikMane0112** [adarsh-singh01/PrithWe#115]

**Comment by adarsh-singh01** [comment]
![image](https://github.com/adarsh-singh01/PrithWe/assets/143992541/4c13eba9-1e20-4fc5-ad38-8851d15d7540)

**Comment by adarsh-singh01** [comment]
Hey @PratikMane0112 , I think keeping the newest on Top is not a good idea... As Sr. No. will be shifted (+1) for every entry... 

What do you think? 

Should we keep the Sr. No. inverted ? 
Like latest is  Sr. no. 4...then 
4
3
2
1

Or 

Keep it just like it is currently.?

**Comment by PratikMane0112** [comment]
As you wish ?

**Comment by PratikMane0112** [comment]
I think sorting by date & time with recent at top would be better ?
