### ISSUE TITLE
Update in UI of History page

### ISSUE THREAD

**Issue by PratikMane0112** [adarsh-singh01/PrithWe#116]

**Comment by PratikMane0112** [comment]
Can you plz also provide the reference for UI of history page ?

**Comment by adarsh-singh01** [comment]
It is same as User Details....

See this image.

![image](https://github.com/adarsh-singh01/PrithWe/assets/143992541/a14b40e1-1224-47e8-8d94-92e70bbf5b26)

**Comment by PratikMane0112** [comment]
Ok, I will do it ASAP.
