### ISSUE TITLE
[Bug:] No dark mode in Tips section

### ISSUE THREAD

**Issue by root-0101** [adarsh-singh01/PrithWe#119]
There is no dark mode in tips section only the color of the text change to white 

https://github.com/adarsh-singh01/PrithWe/assets/142779809/05c802f5-de18-487c-b587-69e7881fef44

**Comment by adarsh-singh01** [comment]
#82... Contributor of this issue is enhancing the dark mode in every page.

**Comment by root-0101** [comment]
ok, I will look for another valid issue
