### ISSUE TITLE
Fix business data UI and other bug (Admin Panel) 

### ISSUE THREAD

**Issue by PratikMane0112** [adarsh-singh01/PrithWe#122]

**Comment by adarsh-singh01** [comment]
Bugs:![IMG_20240612_144831.jpg](https://github.com/adarsh-singh01/PrithWe/assets/143992541/7675da2c-5280-462a-9c23-425ea7c8f6d5)

UI changes in business type users:
It should look collapse until clicked...when clicked entries are shown then chart then recommendation(Everything is same as in household type user... Just remove family member fields and heading.) 
![IMG_20240612_144909.jpg](https://github.com/adarsh-singh01/PrithWe/assets/143992541/660c4cdc-3f31-40a4-8927-72333cc7f278).

**Comment by adarsh-singh01** [comment]
Bugs:![IMG_20240612_144831.jpg](https://github.com/adarsh-singh01/PrithWe/assets/143992541/7675da2c-5280-462a-9c23-425ea7c8f6d5)

UI changes in business type users:
It should look collapse until clicked...when clicked entries are shown then chart then recommendation(Everything is same as in household type user... Just remove family member fields and heading.) 
![IMG_20240612_144909.jpg](https://github.com/adarsh-singh01/PrithWe/assets/143992541/660c4cdc-3f31-40a4-8927-72333cc7f278).

**Comment by PratikMane0112** [comment]
Ok , Understood : )
