### ISSUE TITLE
adding PR template

### ISSUE THREAD

**Issue by mahek0620** [adarsh-singh01/PrithWe#126]

**Comment by Kiran-pande-30** [comment]
Hello @adarsh-singh01 I thing there a necessity of the PR and Issue template

**Comment by adarsh-singh01** [comment]
Send a picture of how it will look after

**Comment by Kiran-pande-30** [comment]
![image](https://github.com/adarsh-singh01/PrithWe/assets/105718863/8da6cd8e-ce67-4de0-814f-5726716ef5f2)
![image](https://github.com/adarsh-singh01/PrithWe/assets/105718863/834ddbe7-7cee-449c-8024-4f0df559b23a)
![image](https://github.com/adarsh-singh01/PrithWe/assets/105718863/18d565ef-11e5-4ae2-8a0c-270bb1ed3821)


These are some of the PR/issue templates used by other open-source organizations. The fields are optional, and we can edit them according to our convenience.
