### ISSUE TITLE
Fix Navbar at top to use it from anywhere in the website

### ISSUE THREAD

**Issue by Utsavladia** [adarsh-singh01/PrithWe#129]
The navbar should be fixed at the top to let the user use it from anywhere in the website and enhance the user experience better.

![image](https://github.com/adarsh-singh01/PrithWe/assets/124615886/8de2520c-1351-4776-bedb-a4fea36a0364)

I would love to contribute to this project.
Please assign this to me under GSSoc 24 🙂

**Comment by adarsh-singh01** [comment]
It   is assigned to someone else  #106

**Comment by adarsh-singh01** [comment]
It   is assigned to someone else  #106
