### ISSUE TITLE
Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by rohitinu6** [adarsh-singh01/PrithWe#130]
I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

Preview of Proposed Website Visitor Widget:

![Screenshot 2024-06-12 143634](https://github.com/adarsh-singh01/PrithWe/assets/113301503/30ee060a-cd8b-485d-a6f7-73f5cf3d1257)

@adarsh-singh01 can you please assign this to me under the **gssoc** label

**Comment by adarsh-singh01** [comment]
Assigned... Make it in such a way that it matches with current UI

**Comment by adarsh-singh01** [comment]
Assigned... Make it in such a way that it matches with current UI

**Comment by adarsh-singh01** [comment]
@rohitinu6 Update??

**Comment by RamakrushnaBiswal** [comment]
hi  @adarsh-singh01 assign it to me i will complete it with in 1 day

**Comment by adarsh-singh01** [comment]
@RamakrushnaBiswal Assigned

**Comment by adarsh-singh01** [comment]
👍
