### ISSUE TITLE
[BUG}: Update UI of Contact Us 

### ISSUE THREAD

**Issue by Kiran-pande-30** [adarsh-singh01/PrithWe#134]
The card for contact is small. it should be around the same size as the signup/login form
![image](https://github.com/adarsh-singh01/PrithWe/assets/105718863/ce44fb68-e1a7-4bb3-a1d7-e5e792f8dd89)

The card for calculating the carbon footprints is also small.
![image](https://github.com/adarsh-singh01/PrithWe/assets/105718863/ee56a6e3-bf22-4f84-8646-f008f8da62d8)

**Comment by adarsh-singh01** [comment]
As of now, there is no need to change the size of cards.please see if you can contribute to any new issue.
