### ISSUE TITLE
[Bug] : Adding Social Media Handles of Founder & Co-founders

### ISSUE THREAD

**Issue by Kiran-pande-30** [adarsh-singh01/PrithWe#135]
1. Adding Founder & Co-founder Social media links
2. Adding Github Links of PrithWe, for more people to see and contribute to the codebase

**Comment by adarsh-singh01** [comment]
> 1. Adding Founder & Co-founder Social media links
> 2. Adding Github Links of PrithWe, for more people to see and contribute to the codebase

Adding social media links of the founder is not planned... Adding Github Links of PrithWe in footer is already assigned to someone else.
