### ISSUE TITLE
[Bug}: Dark Mode - Text Not visible

### ISSUE THREAD

**Issue by Kiran-pande-30** [adarsh-singh01/PrithWe#138]
In Email Verification page, the "time remaining" and "OTP send to your email address" are not visible.
![image](https://github.com/adarsh-singh01/PrithWe/assets/105718863/d66a776c-6070-48ac-8df5-ef2d2710523c)

In Dark Mode - The title of the HouseHold Form is also not visible 
![image](https://github.com/adarsh-singh01/PrithWe/assets/105718863/8a0de9b2-958f-4588-988f-89b817f3b0e5)

**Comment by adarsh-singh01** [comment]
The entire dark mode feature is assigned to another contributor #82
