### ISSUE TITLE
Enhance What is carbon footprint section 

### ISSUE THREAD

**Issue by TANYA03GUPTA** [adarsh-singh01/PrithWe#164]
This section on the home page can be enhanced by adding some pictures some more text . Providnig info on what this ite is actually doing. So i would like to do this and make it more appealing. If possible add the contributionunder GSSOC 24?

**Comment by adarsh-singh01** [comment]
You can work on it but if it doesn't look good we'll not merge it.

**Comment by adarsh-singh01** [comment]
@TANYA03GUPTA did u worked?

**Comment by TANYA03GUPTA** [comment]
No, i have been busy with some other tasks, and could not work on it. You can unassign or close the issue.
