### ISSUE TITLE
Missing Learn.md file

### ISSUE THREAD

**Issue by debangi29** [adarsh-singh01/PrithWe#18]
Add Learn.md file as instructed by Gssoc guidelines

**Comment by debangi29** [comment]
Please assign me the issue @adarsh-singh01 under Gssoc'24

**Comment by adarsh-singh01** [comment]
> Please assign me the issue @adarsh-singh01 under Gssoc'24

Assigned!!

**Comment by adarsh-singh01** [comment]
Can you please give a star to this repository

**Comment by adarsh-singh01** [comment]
hey Debangi, can you please again send a PR by incorporating some changes in the  .env part of the Readme.md

**Comment by debangi29** [comment]
Yeah! Sure.. I am doing it
Thanks
