### ISSUE TITLE
Adding Login/Signup with Google 

### ISSUE THREAD

**Issue by mehrun171** [adarsh-singh01/PrithWe#196]
I want to add Login / Signup with google option to make the login process more easier to the people
Please assign me this task @adarsh-singh01

**Comment by adarsh-singh01** [comment]
It was assigned to someone else earlier and it has been implemented .... check the site ...

**Comment by adarsh-singh01** [comment]
@mehrun171 Do you know Redux or Context Api.... we have to change the current dark mode and light mode feature

**Comment by mehrun171** [comment]
Already the Feature is available na

**Comment by adarsh-singh01** [comment]
> Already the Feature is available na
> 

Yes but it not done using Redux.
