### ISSUE TITLE
Hover effect in card

### ISSUE THREAD

**Issue by root-0101** [adarsh-singh01/PrithWe#20]
It would be great if we add the hover effect which makes the user experience engaging 

![Screenshot 2024-05-30 020937](https://github.com/adarsh-singh01/PrithWe/assets/142779809/bd013e5b-ba1e-4503-aede-fcba97d1e95d)

**Comment by adarsh-singh01** [comment]
> It would be great if we add the hover effect which makes the user experience engaging 
> 
> ![Screenshot 2024-05-30 020937](https://github.com/adarsh-singh01/PrithWe/assets/142779809/bd013e5b-ba1e-4503-aede-fcba97d1e95d)
> 

Assigned!
