### ISSUE TITLE
Add Code of Conduct & Learn.md 

### ISSUE THREAD

**Issue by aasthakourav20** [adarsh-singh01/PrithWe#24]
What's missing in this repository!!
The code of conduct serves as the cornerstone of community interaction, outlining expected behavior and fostering an environment of mutual respect and inclusivity. It sets clear guidelines for communication, collaboration, and conflict resolution, helping to prevent harassment, discrimination, and other negative behaviors. By adhering to a code of conduct, contributors feel safe and valued, which encourages diverse participation and promotes a vibrant and welcoming community.

The learn.md document serves as a centralized resource for learning about the project and its technologies. It provides links to tutorials, documentation, and other educational materials, helping newcomers and experienced developers alike navigate the project and deepen their understanding. By providing access to learning resources, the learn.md document empowers contributors to expand their skills, explore new technologies, and make meaningful contributions to the project.

Please assign this to me under GSSoC'24

**Comment by adarsh-singh01** [comment]
Can you please give a star to this repository
