### ISSUE TITLE
enhancement: Change in design of footer

### ISSUE THREAD

**Issue by avayyyyyyy** [adarsh-singh01/PrithWe#25]
want to change the design of the footer by changing it's layout which increases the user experience.

<img width="611" alt="Screenshot 2024-05-30 at 7 34 31 PM" src="https://github.com/adarsh-singh01/PrithWe/assets/111121419/0bc81593-fc2d-4a65-8ee2-5b8aece8131a">

**Comment by avayyyyyyy** [comment]
Please assign this issue to me!

**Comment by adarsh-singh01** [comment]
Assigned

**Comment by shreyaspathak11** [comment]
Can u assign this issue to me
?
