### ISSUE TITLE
Styling Fixes: Login and Signup card should be at the center

### ISSUE THREAD

**Issue by avayyyyyyy** [adarsh-singh01/PrithWe#26]
want to make the login signup form in the center

<img width="1792" alt="Screenshot 2024-05-30 at 7 37 02 PM" src="https://github.com/adarsh-singh01/PrithWe/assets/111121419/377abfc7-e15b-4f21-a6a0-a73d09d24805">
<img width="1792" alt="Screenshot 2024-05-30 at 7 38 32 PM" src="https://github.com/adarsh-singh01/PrithWe/assets/111121419/59c7feea-c370-48ad-87c2-486d384ab63c">

Please assign this issue to me!

**Comment by adarsh-singh01** [comment]
Hey Shubhankit... Currently these components are not in center because of error arising out a recent merge... They will be fixed by the same guy who caused that.

**Comment by adarsh-singh01** [comment]
Hey Shubhankit... Currently these components are not in center because of error arising out a recent merge... They will be fixed by the same guy who caused that.
