### ISSUE TITLE
Toogle Password

### ISSUE THREAD

**Issue by kushalkumar1362** [adarsh-singh01/PrithWe#27]
Please ensure that the "Toggle Password" feature, which allows users to show or hide and see their password while typing, is added to both the login and sign-up pages. This feature provides convenience and security for users as they enter their passwords.

**Comment by adarsh-singh01** [comment]
Assigned!

**Comment by adarsh-singh01** [comment]
![image](https://github.com/adarsh-singh01/PrithWe/assets/143992541/71b7be31-ab51-4b17-8562-ed2d357b22ba)
hey this error is coming during Build in production...

**Comment by adarsh-singh01** [comment]
fixed that myself ... btw ,Thanks for your contribution
