### ISSUE TITLE
Toggle Button for dark/light mode

### ISSUE THREAD

**Issue by prachita0504** [adarsh-singh01/PrithWe#3]
Dark or light mode button

**Comment by adarsh-singh01** [comment]
Toggle for what?

**Comment by adarsh-singh01** [comment]
> 

Toggle  button for what?

**Comment by adarsh-singh01** [comment]
Do u have acquaintance with tailwindCSS?

**Comment by prachita0504** [comment]
ok

**Comment by prachita0504** [comment]
please add a label of GSSOC and level also

**Comment by adarsh-singh01** [comment]
Can you please give a star to this repository

**Comment by adarsh-singh01** [comment]
Hey Prachita, are you working on it?... Because you haven't forked the Repository yet.

**Comment by prachita0504** [comment]
ya im working

**Comment by adarsh-singh01** [comment]
Hey Prachita, Can you kindly complete this task by tomorrow?...as there are several other contributors also that are showing their interest in doing this task .

**Comment by prachita0504** [comment]
ok

**Comment by adarsh-singh01** [comment]
I will be closing this issue at 9PM...you can work on other issues...else see if you can complete this.

**Comment by prachita0504** [comment]
done
