### ISSUE TITLE
Hamburger on Mobile screen 

### ISSUE THREAD

**Issue by kushalkumar1362** [adarsh-singh01/PrithWe#31]
# problem 
- when i click on any option from Hamburger the hamburger will not be closed automatically.
# solution 
- add functionality when user click on any navbar option the navbar will be closed automatically 

![Screenshot_20240531-080559.png](https://github.com/adarsh-singh01/PrithWe/assets/140513098/a94a6d4c-b977-4c0f-91ad-d2cd3855576e)

**Comment by adarsh-singh01** [comment]
Assigned
