### ISSUE TITLE
FEAT : Password toggling eye button for signup page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [adarsh-singh01/PrithWe#33]
I will add password toggling eye button for sign up page so that user will  get an option to hide or show the password while entering password in the password field .

![Screenshot 2024-05-31 112412](https://github.com/adarsh-singh01/PrithWe/assets/118350936/d0d9b720-fbdb-4425-91c9-006d0075490f)

**Comment by adarsh-singh01** [comment]
Hey Ayushmaan, This has already been done by some other contributor, We just need to merge that PR. 

See if you can do something else... I have opened  several issues also.
