### ISSUE TITLE
Adding Mail Verification

### ISSUE THREAD

**Issue by SamarthUrane** [adarsh-singh01/PrithWe#35]
Implement email verification for user registration to enhance security and reliability. This involves sending a otp  upon registration, which users must enter to confirm their email addresses. The feature aims to prevent spam, improve account security, and enhance user experience.

**Comment by SamarthUrane** [comment]
Please assign me this issue under GSSOC'24

**Comment by adarsh-singh01** [comment]
How will you be doing this kindly explain in short.

**Comment by SamarthUrane** [comment]
I can use Nodemailer service to send a random 6 digit number to a user's mail and same will be saved to his account database. Before user login I will check if user is verified or not if not verified I will ask them to fill this 6 digit otp after that I will mark that user as verified and then I will allow user to login.

**Comment by adarsh-singh01** [comment]
> I can use Nodemailer service to send a random 6 digit number to a user's mail and same will be saved to his account database. Before user login I will check if user is verified or not if not verified I will ask them to fill this 6 digit otp after that I will mark that user as verified and then I will allow user to login.

Assigned!

**Comment by SamarthUrane** [comment]
I have solved this issue please check PR #40  and merge this.
