### ISSUE TITLE
Adding sticky header 

### ISSUE THREAD

**Issue by Che140401** [adarsh-singh01/PrithWe#41]
Sticky header will improve user interface

https://github.com/adarsh-singh01/PrithWe/assets/109230049/4e6614d0-7158-4a3f-8107-50d74183c700

https://github.com/adarsh-singh01/PrithWe/assets/109230049/399622bc-7848-43ea-8fbe-a13e16604689

**Comment by adarsh-singh01** [comment]
#21 see this... if you can solve this issue...then comment on that issue...i will ask that contributor to pass it to you
