### ISSUE TITLE
Accordian for information

### ISSUE THREAD

**Issue by Che140401** [adarsh-singh01/PrithWe#42]
We can ensure you if we can shorter the page by wrap in accordian 

https://github.com/adarsh-singh01/PrithWe/assets/109230049/b6f44a19-e240-42b1-8265-d09fe6b3ac5c

longer page without accordian

https://github.com/adarsh-singh01/PrithWe/assets/109230049/85b9bdc7-7e4c-44e1-a0be-448c55d65a82

**Comment by adarsh-singh01** [comment]
> We can ensure you if we can shorter the page by wrap in accordian 
> 
> 
> https://github.com/adarsh-singh01/PrithWe/assets/109230049/b6f44a19-e240-42b1-8265-d09fe6b3ac5c
> 
> longer page without accordian
> 
> https://github.com/adarsh-singh01/PrithWe/assets/109230049/85b9bdc7-7e4c-44e1-a0be-448c55d65a82
> 
> 

Hey Chetan, I do not want an accordion for my information page... But I would like to have it in my Homepage as a FAQ section... Can you make it?

**Comment by Che140401** [comment]
Are you talking about this section

![Screenshot 2024-06-02 195119](https://github.com/adarsh-singh01/PrithWe/assets/109230049/f1631629-74b2-4c11-8a6a-ea413f31e1ab)

**Comment by adarsh-singh01** [comment]
No. I want to make a New section named FAQs. 

Which will be in accordion format.

**Comment by Che140401** [comment]
yeah provide me data i will make new section

**Comment by Che140401** [comment]
provide me question and answers format i will do it

**Comment by adarsh-singh01** [comment]
Okay, I will send you soon.

**Comment by Che140401** [comment]
Hey bro is there any update

**Comment by adarsh-singh01** [comment]
> Hey bro is there any update

Hello sorry, got caught up in some work... Will send by 11.59pm

**Comment by adarsh-singh01** [comment]
FAQ
1. What is PrithWe?
Answer: PrithWe is a comprehensive carbon footprint calculator designed for both households and businesses. It helps users estimate their carbon emissions and provides insights on how to reduce them. By understanding and managing their carbon footprints, users can contribute to a more sustainable future.

2. How do I use the carbon footprint calculator?
Answer: Using PrithWe's carbon footprint calculator is easy! Simply log in, select whether you are a household or a business, and fill in the required details about your energy consumption, transportation habits, and other activities. The calculator will then provide you with an estimate of your carbon emissions and it shows interactive charts from which you can take steps for reducing your environmental impact.

3. I forgot my password. What should I do?
Answer: If you forgot your password, click on the "Forgot Password" button on the login page. Enter your email address, and an OTP (One-Time Password) will be sent to you. Use the OTP to reset your password and regain access to your account.

4. Why is it important to calculate my carbon footprint?
Answer: Calculating your carbon footprint is crucial for understanding your personal or organizational impact on the environment. By knowing how much carbon dioxide and other greenhouse gases you are responsible for, you can take steps to reduce your emissions, conserve resources, and contribute to the fight against climate change.

**Comment by adarsh-singh01** [comment]
kindly do not copy As It is from the accordian templates from flowbite or any tailwind library.
it should match the UI of current website

**Comment by Che140401** [comment]
Sure we will try to keep simple as possible
