### ISSUE TITLE
[Feature] Add Custom Scrollbar 

### ISSUE THREAD

**Issue by SwanandD121** [adarsh-singh01/PrithWe#44]
**Description:**
The platform currently lacks the functionality of theme-matching scrollbar which are pivotal for improving user comfort and navigation fluidity. By integrating this feature, I aim to provide users with a smoother and more personalized browsing experience.

I have implemented this feature multiple times in open source as well as personal projects, so please assign this issue to me under GSSoC'24.

**Comment by adarsh-singh01** [comment]
Hey Swanand , i have assigned you the issue

**Comment by SwanandD121** [comment]
> Hey Swanand , i have assigned you the issue

Thanks, I'll start working on it asap!
