### ISSUE TITLE
Adding a Admin dashboard 

### ISSUE THREAD

**Issue by SamarthUrane** [adarsh-singh01/PrithWe#48]
Adding a admin dashboard that only admin can access. Admin can see all users and can see contact forms submitted by user

**Comment by SamarthUrane** [comment]
Please assign me this issue under GSSOC'24

**Comment by adarsh-singh01** [comment]
Assigned!

**Comment by SamarthUrane** [comment]
@adarsh-singh01 how do you want to enter in admin dashboard?
There are some ways I can think of :-
1. We can create a  "Login as Admin" Button in Home page (I personal not recommend it will not a good user experience)
2. We can create direct route where admin have to manual enter special route like in wordpress e.g /loginForAdmin
3. In current login setup if admin's email and password entered then go to admin dashboard

**Comment by adarsh-singh01** [comment]
> @adarsh-singh01 how do you want to enter in admin dashboard?
> There are some ways I can think of :-
> 1. We can create a  "Login as Admin" Button in Home page (I personal not recommend it will not a good user experience)
> 2. We can create direct route where admin have to manual enter special route like in wordpress e.g /loginForAdmin
> 3. In current login setup if admin's email and password entered then go to admin dashboard

2nd and 3rd looks fine...which will be best according to you?... I think the 3rd is good.
