### ISSUE TITLE
[Bug] Errors in CONTRIBUTION.md file.

### ISSUE THREAD

**Issue by SwanandD121** [adarsh-singh01/PrithWe#51]
In the [CONTRIBUTION.md](https://github.com/adarsh-singh01/PrithWe/blob/main/CONTRIBUTION.md) file, the contributing steps seem to be given for some other project. It says to create gaming files while your website doesn't have any content related to gaming.

It needs to change as soon as possible as some contributors might end up following that which could possibly ruin the original project.

I propose to solve this error by modifying the file with reference to the Diabetes Prediction project. Please assign me this issue under GSSoC'24.

**Comment by adarsh-singh01** [comment]
didn't saw that...okay fix that

**Comment by SwanandD121** [comment]
> didn't saw that...okay fix that

Alright, on it.
