### ISSUE TITLE
New Page nor ewndering from top

### ISSUE THREAD

**Issue by paulkrishanu4** [adarsh-singh01/PrithWe#55]
New page should render from top automatically when we navigate to that page.
Assign me this issue

https://github.com/adarsh-singh01/PrithWe/assets/169196836/75aaaa4c-25c6-41af-a30f-324079936019

**Comment by adarsh-singh01** [comment]
Assigned!

**Comment by adarsh-singh01** [comment]
Can you do one more thing... When the result page is rendered after clicking on calculate carbon footprint button... It also do not render from top...can u fix that?

**Comment by paulkrishanu4** [comment]
okay sir I will fix it
