### ISSUE TITLE
Adding a forgot password feature

### ISSUE THREAD

**Issue by SamarthUrane** [adarsh-singh01/PrithWe#58]
The "forgot password" feature allows users to reset their passwords if forgotten. Users provide their email , receive a verification OTP via email, and set a new password securely. Thorough testing ensures reliable functionality and enhances account security.

**Comment by SamarthUrane** [comment]
Please assign me this under GSSOC'24

**Comment by adarsh-singh01** [comment]
Hey Samarth,
This error is coming while deploying into production.
![image](https://github.com/adarsh-singh01/PrithWe/assets/143992541/466107eb-b9dc-49fa-93f3-055cac78fd87)

**Comment by SamarthUrane** [comment]
Ok I will look into it right now

**Comment by adarsh-singh01** [comment]
Changes that i did was adding these in .env
PGSSLMODE='require'
MAIL="prithwecalc@gmail.com"
APP_PASSWORD="passwordispassword"

**Comment by SamarthUrane** [comment]
Please remove PGSSLMODE='require' from .env and then check

**Comment by adarsh-singh01** [comment]
> Please remove PGSSLMODE='require' from .env and then check

It worked... Thanks for your contribution

**Comment by adarsh-singh01** [comment]
Got merged and deployed in one go without any errors... 👏
