### ISSUE TITLE
React Bug

### ISSUE THREAD

**Issue by adarsh-singh01** [adarsh-singh01/PrithWe#6]
In client/src/components/Header.jsx
Line no. 146
The page is being force reload... Else the log out functionality is not being executed...

If You have Good knowledge of React Hooks... And if you can fix this... Do this.

**Comment by Ayushmaanagarwal1211** [comment]
I wanna work on that

**Comment by adarsh-singh01** [comment]
> I wanna work on that 

![IMG_20240531_172037.jpg](https://github.com/adarsh-singh01/PrithWe/assets/143992541/6956629c-d370-4eb9-b544-a096fc368220)

Sorry again brother,someone else asked me for it earlier.

**Comment by Ayushmaanagarwal1211** [comment]
No problem bro
