### ISSUE TITLE
Adding icons on the navbar

### ISSUE THREAD

**Issue by harshmishra19** [adarsh-singh01/PrithWe#62]
Adding icons on the navbar can make your website look more appealing

![Screenshot 2024-05-14 215142](https://github.com/adarsh-singh01/PrithWe/assets/115486960/70ad2522-a393-498d-a1e9-6341766cbb0f)
![Screenshot 2024-05-17 094153](https://github.com/adarsh-singh01/PrithWe/assets/115486960/88db89c5-c7cd-4af4-aa7a-375eda3f54c2)

**Comment by adarsh-singh01** [comment]
Hey Harsh
as of now ,we think we dont need this ...will let you know in future ,if there is need.
