### ISSUE TITLE
Adding google login and signup functionality

### ISSUE THREAD

**Issue by harshmishra19** [adarsh-singh01/PrithWe#63]
![login](https://github.com/adarsh-singh01/PrithWe/assets/115486960/db377561-c260-41ad-a525-6f64fa9dfd97)

**Comment by adarsh-singh01** [comment]
How will you be doing this?... Passport OAuth?

**Comment by harshmishra19** [comment]
yes

**Comment by adarsh-singh01** [comment]
Assigned

**Comment by adarsh-singh01** [comment]
Are you doing this?

**Comment by harshmishra19** [comment]
Yess

**Comment by adarsh-singh01** [comment]
@HarshitaJaiswal5 assigned

**Comment by adarsh-singh01** [comment]
@HarshitaJaiswal5 Are u working on it?
