### ISSUE TITLE
[Feat]: Add Pre-Loader and Custom Cursor

### ISSUE THREAD

**Issue by shreyash3087** [adarsh-singh01/PrithWe#65]
**Description:**

I would like to suggest adding a custom loading screen to enhance the user experience on the platform along with a custom cursor. This feature will allow for a more engaging user experience. I have already designed the components and am willing to implement them.

**Proposed Changes:**

Pre-Loader: A minimilistic loading screen that matches the website's color scheme and looks elegant and clean.
Cursor: A Simple but elegant looking cursor trail that makes the website more engaging

**Design:**

I have attached the designs below:

**Spinner-**

![screencapture-localhost-5173-2024-06-03-10_11_03](https://github.com/adarsh-singh01/PrithWe/assets/72603662/3ce1044b-b92b-4d16-ad61-83764669f519)

**Curosr-**

https://github.com/adarsh-singh01/PrithWe/assets/72603662/5193831a-be4e-4b4e-9ba2-ebaa54722392

**Additional Context:**

I am happy to contribute by implementing these features myself. Please let me know if you have any feedback or additional requirements.

[X] I am a GSSOC'24 Contributor

Thank you for considering my request!

**Comment by shreyash3087** [comment]
@adarsh-singh01 kindly assign me the issue,i have the fetures ready,just need to be assigned

Also Please do tell if there are any additional requirements/suggestions

**Comment by adarsh-singh01** [comment]
Assigned!
