### ISSUE TITLE
Adding User Details Section in Admin DashBoard

### ISSUE THREAD

**Issue by SamarthUrane** [adarsh-singh01/PrithWe#69]
Admin can click on a particular user and can see his complete history consisting of his household or business calculator history, family members etc. basically everything that are stored in database in organized manner. This will enable admin to keep track of everything done by user and their data.

**Comment by SamarthUrane** [comment]
Please assign me this under GSSOC'24

**Comment by adarsh-singh01** [comment]
Hey Samarth, currently the household form is having many bugs and it is currently not submitting the responses because of the merge of this PR.#17 ...you can work on the issue raised by you once the bugs are fixed. 

://github.com/adarsh-singh01/PrithWe/pull/17#issuecomment-2143743117...

**Comment by SamarthUrane** [comment]
Yea sure I will wait till then

**Comment by adarsh-singh01** [comment]
The bugs have been solved ...you can start doing it.

**Comment by SamarthUrane** [comment]
Please add a GSSOC label and level also

**Comment by SamarthUrane** [comment]
Hey, @adarsh-singh01 Is the deployed website code is different from the current main branch code?

**Comment by adarsh-singh01** [comment]
> Hey, @adarsh-singh01 Is the deployed website code is different from the current main branch code?

No, render is deploying the same code that is on the Github... When any commit happens then render starts the deploy again.
 
So it's Up to date with the code which is in GitHub.

**Comment by SamarthUrane** [comment]
Hey @adarsh-singh01 can you just check if in business_common table data is stored or not.
In my end I think their is some issue in storing data I is showing null for all values in the table
