### ISSUE TITLE
React bug in LOGIN

### ISSUE THREAD

**Issue by adarsh-singh01** [adarsh-singh01/PrithWe#7]
In client/src/components/Header.jsx
Line no. 25
The page is being force reload... Else the LOGIN functionality is not being executed...

If You have Good knowledge of React Hooks... And if you can fix this... Do this.

**Comment by Tomkndn** [comment]
Hey, I want to work on this project.
Kindly assigne this issue to me. So that I can start working on this project

**Comment by Tomkndn** [comment]
What should be the value for the JWT_SECRET in the .env file.

**Comment by adarsh-singh01** [comment]
We have made some changes in our environment variable part of Readme.md 
Please see that. 

Actually that secret value can be any string (ex: "secretVal") This value is used to sign/encrypt the SessionID.

**Comment by Tomkndn** [comment]
Okay, understood.

**Comment by adarsh-singh01** [comment]
Can you please give a star to this repository.

**Comment by Tomkndn** [comment]
It seems like in the logout button the same force reload is happening should I fixed that too.

**Comment by adarsh-singh01** [comment]
> It seems like in the logout button the same force reload is happening should I fixed that too.
> 

Yeah sure
