### ISSUE TITLE
[Bug]: HouseHold Form doesn't work

### ISSUE THREAD

**Issue by shreyash3087** [adarsh-singh01/PrithWe#74]
**Description:**

The Household form doesn't work, clicking on calculate button doesn't perform the intended calculations.

**Steps to Reproduce:**

- Go to PrithWe's Site: https://prithwe.onrender.com/
- Login using your credentials.
- Fill the Household form.
- Notice nothing happens when clicked on the calculate button.

**Screenshots:**

![screencapture-prithwe-onrender-2024-06-04-09_58_12](https://github.com/adarsh-singh01/PrithWe/assets/72603662/9e9efab6-c23d-47e3-9c8c-08c95961fd9f)

**Additonal Context:**

I am happy to contribute by fixing this bug myself. Please let me know if you have any feedback or additional requirements.

[X] I am a GSSOC'24 Contributor

Thank you for considering my request!

**Comment by shreyash3087** [comment]
@adarsh-singh01 I noticed that a previous merge was the reason for this bug, also the change in form's ui is caused because of the merge as well,even though the pr has been merged, i can manually revert back the changes in ui and add proper input sanitization to ensure proper functionality of the website.

Would  you like to assign me this issue? I'll try and fix it ASAP

**Comment by adarsh-singh01** [comment]
Assigned!

**Comment by adarsh-singh01** [comment]
Hey... Need some changes in cursor... Please see PR #70
