### ISSUE TITLE
After opening dialog box by click on hamburger that icon should be close icon

### ISSUE THREAD

**Issue by kapilG0** [adarsh-singh01/PrithWe#76]
![Screenshot_20240604_162200](https://github.com/adarsh-singh01/PrithWe/assets/59639410/23312406-0c19-480e-b689-32d87b45356a)

**Comment by kapilG0** [comment]
Hello @adarsh-singh01 please assign this issue to me under gssoc 24

**Comment by adarsh-singh01** [comment]
Will you add animation to it?...it will turn into X from three sticks?...when user clicks on it

**Comment by kapilG0** [comment]
> Will you add animation to it?...it will turn into X from three sticks?...when user clicks on it

It will turn into X from three sticks if user opens it and in close state again three sticks will come up

**Comment by adarsh-singh01** [comment]
> > Will you add animation to it?...it will turn into X from three sticks?...when user clicks on it
> 
> It will turn into X from three sticks if user opens it and in close state again three sticks will come up

Ok... Assigned

**Comment by kapilG0** [comment]
Hello @adarsh-singh01 i raised pr #99 for this issue. please check.
