### ISSUE TITLE
[Enhancment] Adding Professional Look to the Email being send for verifying otp

### ISSUE THREAD

**Issue by falgun143** [adarsh-singh01/PrithWe#77]
**Description**
As we know when a email is being send to the user for otp verification it looks very simple as shown below
![image](https://github.com/adarsh-singh01/PrithWe/assets/105922142/7da8f6be-8eee-4e3e-8847-004517116916)
We can make it look good by adding logo ,links to the site like github,instagram etc....
And would look something like this finally
![image](https://github.com/adarsh-singh01/PrithWe/assets/105922142/85878c97-b01b-443c-9cc9-97ff21cdcf16)
@adarsh-singh01 any thoughts??

**Comment by falgun143** [comment]
@adarsh-singh01  If that is okay please assign it to me under gssoc

**Comment by adarsh-singh01** [comment]
That's a really nice idea...

**Comment by adarsh-singh01** [comment]
Assigned!

**Comment by adarsh-singh01** [comment]
Btw, Try to make our OTP email better than Unacademy's 🙂
