### ISSUE TITLE
[BUG]: Invalid Input Sanitization

### ISSUE THREAD

**Issue by aryansharma220** [adarsh-singh01/PrithWe#8]
![image](https://github.com/adarsh-singh01/PrithWe/assets/133234867/76e56049-5742-458c-a6ad-2c317b9f2aee)

The input allowed to be entered should be numerical and proper error should be given if user enters invalid input.

Please assign it to me under gssoc24

**Comment by adarsh-singh01** [comment]
> ![image](https://github.com/adarsh-singh01/PrithWe/assets/133234867/76e56049-5742-458c-a6ad-2c317b9f2aee)
> 
> The input allowed to be entered should be numerical and proper error should be given if user enters invalid input.
> 
> Please assign it to me under gssoc24

Actually, we are throwing an error in the form of toast message when user tries to submit invalid values... You can be assigned this task if you could please elaborate/tell what will you do?

**Comment by adarsh-singh01** [comment]
> > > ![image](https://github.com/adarsh-singh01/PrithWe/assets/133234867/76e56049-5742-458c-a6ad-2c317b9f2aee)
> > > 
> > > The input allowed to be entered should be numerical and proper error should be given if user enters invalid input.
> > > 
> > > Please assign it to me under gssoc24
> > 
> > Actually, we are throwing an error in the form of toast message when user tries to submit invalid values... You can be assigned this task if you could please elaborate/tell what will you do? 
> 
> We can put the prompt beneath each input fields so that the error can be shown at real time not after filling the complete form as it would be quicker for the users.

Okay nice idea... I am assigning you the task.

**Comment by adarsh-singh01** [comment]
Can you please give a star to this repository

**Comment by aryansharma220** [comment]
> Can you please give a star to this repository

done
