### ISSUE TITLE
[Enhancement] Enhancing the dark mode theme.

### ISSUE THREAD

**Issue by SwanandD121** [adarsh-singh01/PrithWe#82]
**Description:**
The current dark mode colours are a bit off. With four different dark colours used, the website lacks the consistency. The dark theme should consist of multiple shades of the same colour and should look subtle.

Also the theme changes at once without any animation. The smooth transition from dark to light and vice versa would help in making the user interface better.

**Approach:**
The dark theme should have some gradient or texture so that it looks professional. Also using consistent colours, preferably the blue shade to match with the theme would be great.

Assign me this issue under GSSOC'24.

**Comment by adarsh-singh01** [comment]
Assigned... Btw I was just about to raise this issue.

**Comment by SwanandD121** [comment]
> Assigned... Btw I was just about to raise this issue.

Alright, I'll start working on it.

**Comment by shreyaspathak11** [comment]
can you assign this to me?

**Comment by adarsh-singh01** [comment]
> can you assign this to me?
> 

Sorry brother , this task is already assigned to another contributor.

**Comment by SwanandD121** [comment]
@adarsh-singh01 Hey, the current Dark Mode implementation made by a fellow contributor is somewhat difficult to understand. There is no state management used (as far as I can understand).
I'll need to add all that and I'll be using Redux for the purpose, so it may take some more time... just letting you know.
Also if would just drop your discord here, it will be great.

**Comment by adarsh-singh01** [comment]
> @adarsh-singh01 Hey, the current Dark Mode implementation made by a fellow contributor is somewhat difficult to understand. There is no state management used (as far as I can understand).
> I'll need to add all that and I'll be using Redux for the purpose, so it may take some more time... just letting you know.
> Also if would just drop your discord here, it will be great.

Okay
Actually I am not very active on discord... I often use LinkedIn and X... Their links are in my profile.

**Comment by adarsh-singh01** [comment]
@SwanandD121 Why are you not responding?
