### ISSUE TITLE
Bug : UI Imperfection on Email verification page

### ISSUE THREAD

**Issue by ansh-h-mehta** [adarsh-singh01/PrithWe#89]
The dialogue box looks weird due to uneven shape, making the UI look imperfect.

![image](https://github.com/adarsh-singh01/PrithWe/assets/99081110/a6ee63df-f8e3-4493-a1d7-578a93dc1e72)

**Comment by adarsh-singh01** [comment]
there is imperfection in the UI of reset password also...make them by taking inspiration from login/signup/contact us pages

**Comment by ansh-h-mehta** [comment]
Thanks @adarsh-singh01 I've noted your requirement, I will implement the changes accordingly.
