### ISSUE TITLE
A new feature of History tab

### ISSUE THREAD

**Issue by adarsh-singh01** [adarsh-singh01/PrithWe#9]
We want to show the user the history of his/her previous carbon footprints along with the entries that he made and a button to show the Donutchart... 

In making the UI use Tailwindcss.

**Comment by Tomkndn** [comment]
Hey, I want to work on this project looks interesting to me.
Kindly, assign this issue too.

**Comment by Tomkndn** [comment]
I have a doubt, When I click on calculate it does send the data to the database or it does nothing?

**Comment by adarsh-singh01** [comment]
It saves all the inputs in the database... Currently the household form is not working... A PR caused errors in that...business form is working fine.

**Comment by Tomkndn** [comment]
So for business form I have to make a history section?

**Comment by adarsh-singh01** [comment]
History section will be made for both household and business section... As the bug in household form will be solved very soon

**Comment by Tomkndn** [comment]
Is that issue is open or assigned to anybody.

**Comment by Tomkndn** [comment]
Let me know when the issue will be solved.

**Comment by adarsh-singh01** [comment]
Okay

**Comment by adarsh-singh01** [comment]
The bugs have been solved , you can start working on it.

**Comment by Tomkndn** [comment]
okay!

**Comment by Tomkndn** [comment]
The calculated value and the entries is not been saved to the database, 
So, should I copy paste the function for calculating the total value for showing the chart? or anything else.

**Comment by Tomkndn** [comment]
The carbon footprints and label value for the charts is not bein saved in the database.
So, should I copy paste the function to calculate the values? or anything else.
Also the carbon entries is being rendered in the history page should we include the family member details too?

**Comment by adarsh-singh01** [comment]
![image](https://github.com/adarsh-singh01/PrithWe/assets/143992541/86c9700f-b4df-4327-8f9d-a8ce86af52fe)
the entries are being saved in the database (example above)...

the label value and total carbon footprint is not being saved in the database...copy paste the function to calculate the values can be done ....but if you can find any other way in which you do not need to copy paste the same function...then implement that.

like storing the formula in a separate file and accessing it from history and calculator page both.

**Comment by adarsh-singh01** [comment]
the business form has blank entries in it...there is a minor error...we'll fix that tomorrow...till then you can make  for household

**Comment by Tomkndn** [comment]
What about the family entries? should we display it in the history section? or only the normal inputs?

**Comment by adarsh-singh01** [comment]
> What about the family entries? should we display it in the history section? or only the normal inputs?

Have you shown family entries or not?...

**Comment by Tomkndn** [comment]
no, bcz without the family entries it is looking fine from my side.
Rest is upto you.

**Comment by SamarthUrane** [comment]
Please assign me this issue
