### ISSUE TITLE
Updating UI for user details and adding date field

### ISSUE THREAD

**Issue by SamarthUrane** [adarsh-singh01/PrithWe#90]
Updating the User Details UI as mentioned in the PR #88 and adding date in bussiness_common and household_common to know when the user had done the calculation request.

**Comment by SamarthUrane** [comment]
Assign me this issue under GSSOC'24

**Comment by adarsh-singh01** [comment]
Are you interested in doing the AI integration to show personalized recommendations to reduce their carbon footprints based on user inputs? 

I am raising an issue regarding that... If you want I can assign you that right away.

**Comment by SamarthUrane** [comment]
Yeah I can use AI API of  for doing that

**Comment by SamarthUrane** [comment]
But If you want to create your own model that I can't do

**Comment by adarsh-singh01** [comment]
i m not thinking to create my own model...just want to use  gemini/chatgpt to generate recommendations.

**Comment by SamarthUrane** [comment]
Yeah then I am interested to work with that

**Comment by SamarthUrane** [comment]
Please raise Issue for that and assign me

**Comment by SamarthUrane** [comment]
I have created the issue for the same please assign me that issue

**Comment by SamarthUrane** [comment]
Hey @adarsh-singh01, Actually I will not be available to solve this issue due to some reasons sorry about that. 
My roommate is interested in this issue and he can solve it please assign this to him. I have told him about the requirements.

**Comment by PratikMane0112** [comment]
Can you plz assign this to me ?

> Hey @adarsh-singh01, Actually I will not be available to solve this issue due to some reasons sorry about that. My roommate is interested in this issue and he can solve it please assign this to him. I have told him about the requirements.

**Comment by adarsh-singh01** [comment]
Assigned

**Comment by PratikMane0112** [comment]
Thanks, I will do it by tomorrow EOD.

**Comment by adarsh-singh01** [comment]
![337412630-e5ee9231-2a0a-4ed5-b49b-f387a71e7257 (1).png](https://github.com/adarsh-singh01/PrithWe/assets/143992541/ac3a329b-f1e2-4450-9fe5-29155b0b30f0)
