### ISSUE TITLE
Enhancing UI of Founders Section in About Us page

### ISSUE THREAD

**Issue by asthanegi14** [adarsh-singh01/PrithWe#91]
Currently About Us page looks like this:-

![Screenshot (979)](https://github.com/adarsh-singh01/PrithWe/assets/93486108/953e1a22-e173-4aa3-a663-bd850dbeef15)

I want to update it and make it something like this:-

![img](https://github.com/adarsh-singh01/PrithWe/assets/93486108/77046f31-c4a9-47a8-be7e-8422bcb3dec5)

**Comment by adarsh-singh01** [comment]
Hey Astha,As of now we don't think it will look good on our website as there are only people currently... Please see if you can contribute anything else on the website.

**Comment by adarsh-singh01** [comment]
Kindly give a star to this repo

**Comment by asthanegi14** [comment]
The main idea is to display more information about the founders, not the carousel slider. I think it will look good, but the decision is yours, @adarsh-singh01 .
