### ISSUE TITLE
[Feature]  Adding Two way Email Communication between Admin and Client

### ISSUE THREAD

**Issue by falgun143** [adarsh-singh01/PrithWe#93]
**Description**

As we know when the user submits contact form.
![image](https://github.com/adarsh-singh01/PrithWe/assets/105922142/71d4894e-08b0-4299-883a-f901a92c1dd1)

The data just gets stored inside the data base and It would be inefficient for the admin to always check the data base and see who contacted them ,So I would like to add the following feature.
1. When ever the user submits the form the data should be send to the admin ,Which will look something like this
![image](https://github.com/adarsh-singh01/PrithWe/assets/105922142/55d28d7f-f15f-48ac-b6a3-6b3e4fd2748c)
2.An automatic mail should be send to the user from the server saying thank you for contacting our mentor will connect with you within two  working days something like that.

This is the architecture.
![image](https://github.com/adarsh-singh01/PrithWe/assets/105922142/2d00e14d-2d4b-4e1c-9242-1ceb9266a733)

Additions:
In my last pr #86 ,I haven't added the otp validity of 10 min,I will add the chages with this issue it self  if you assign me a higher level of label is that okay ?

**Comment by falgun143** [comment]
@adarsh-singh01 any thoughts?

**Comment by adarsh-singh01** [comment]
Assigned!... Labelled it as level3

**Comment by falgun143** [comment]
@adarsh-singh01 Do three things.

1. Go to server and delete the folder EmailTemplate as I have already created the EmailTemplates folder which contains all the email templates.

2. And if this code
const getHtmlTemplate = (otp) => {

const templatePath = path.resolve(__dirname, "EmailTemplates", "SendOtp.html");

const templatePath = path.resolve(__dirname, "EmailTemplate", "emailTemplate.html");

let template = fs.readFileSync(templatePath, "utf8");
return template.replace("{{otp}}", otp);
};)

is in SendOTP.js then remove the line  const templatePath = path.resolve(__dirname, "EmailTemplate", "emailTemplate.html");

4. And also ensure SendContactEmail.js matches with the code given below.

import nodemailer from "nodemailer";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config();

// Error handling wrapper
const wrapAsync = (fn) => {
  return (...args) => {
    fn(...args).catch((err) => {
      console.error(err); // Log the error
    });
  };
};

// Nodemailer transporter configuration
let transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false, // true for 465, false for other ports
  requireTLS: true,
  auth: {
    user: process.env.MAIL,
    pass: process.env.APP_PASSWORD 
  },
});

const getFormDataHtmlTemplate = (name,email,message) => {
  const templatePath = path.resolve(__dirname, "EmailTemplates", "FormData.html");
  let template = fs.readFileSync(templatePath, "utf8");
  template=template.replace("{{name}}", name);
  template=template.replace("{{email}}", email);
  template=template.replace("{{message}}", message);
  return template;
};

// Function to receive contact data and send an email
export const ReceviceContactData = (async (name, email, message, subject) => {
  const htmlContent=getFormDataHtmlTemplate(name,email,message);
  try { 
    const mailOptions = {  
      from:email,
      to: process.env.MAIL,
      subject: subject,
      html:htmlContent
    };
    await transporter.sendMail(mailOptions);
  } catch (error) {
    console.error("Error sending email:", error);
  }
});

// Function to get HTML template and replace name placeholder
const getThankYouHtmlTemplate = (name) => {
  const templatePath = path.resolve(__dirname, "EmailTemplates", "ThankYou.html");
  let template = fs.readFileSync(templatePath, "utf8");
  return template.replace("{{name}}", name);
};

// Function to send an email with an HTML template
export const sendContactEmail = (async (name, email,  subject) => {
  const htmlContent = getThankYouHtmlTemplate(name);
  try { 
    const mailOptions = {  
      from: process.env.MAIL,
      to: email,
      subject: subject,
      html: htmlContent 
    };
    await transporter.sendMail(mailOptions);
  } catch (error) {
    console.error("Error sending  email:", error);
  }
});

**Comment by falgun143** [comment]
@adarsh-singh01 Let me know if any errors are still there

**Comment by adarsh-singh01** [comment]
Errors have been Fixed... Thanks
