### ISSUE TITLE
AI integration to show personalized recommendations to reduce their carbon footprints based on user inputs

### ISSUE THREAD

**Issue by SamarthUrane** [adarsh-singh01/PrithWe#94]
Integrating AI to show recommendations to reduce carbon footprint. In case of household recommendations will be member based every member will get personalize recommendation In the case of business it will get overall recommendations according to their inputs.

**Comment by SamarthUrane** [comment]
Please assign me this issue under GSSOC'24

**Comment by SamarthUrane** [comment]
Hey @adarsh-singh01 Do you want to save this recommendation to database?

**Comment by SamarthUrane** [comment]
Where should I show this recommendations?
Is it OK if I show recommendation below the generated graph for carbon footprint?

**Comment by adarsh-singh01** [comment]
> Hey @adarsh-singh01 Do you want to save this recommendation to database? 

Yes... BtwWhat's your take

**Comment by adarsh-singh01** [comment]
> Where should I show this recommendations?
> Is it OK if I show recommendation below the generated graph for carbon footprint?

Yes, show it below the graph.

**Comment by SamarthUrane** [comment]
> > Hey @adarsh-singh01 Do you want to save this recommendation to database?
> 
> Yes... Btw What's your take?

If we want to show this recommendation shown to user again then it is good to save it in database.

**Comment by SamarthUrane** [comment]
Do want to show recommendation anywhere else ?
Maybe we can show in history tab as well.
Is that page ready?

**Comment by adarsh-singh01** [comment]
> Do want to show recommendation anywhere else ?
> Maybe we can show in history tab as well.
> Is that page ready?

Yes, we'll show it in history tab

The person who was assigned that issue has sent a PR but i suggested some changes and he is currently not replying.

**Comment by adarsh-singh01** [comment]
Do you want to work on the history page... Because I think it can be made the same as #90 but in spite of showing everyone's data only his/her data will be shown... Along with the Total Carbon Footprint, Chart, Recommendation....

**Comment by SamarthUrane** [comment]
Yeah sure I can work on it

**Comment by adarsh-singh01** [comment]
> Yeah sure I can work on it 

Where should I assign you that... In the issue or in the PR Or Both...

**Comment by SamarthUrane** [comment]
Assign in the history issue. It will keep the PR specific

**Comment by SamarthUrane** [comment]
Should I request their or you can directly assign?

**Comment by adarsh-singh01** [comment]
Btw I don't want to remove the previous guy from the assigned...he may feel bad bcoz He has made some progress already... You can carry on that Or you can rewrite the whole thing...

**Comment by adarsh-singh01** [comment]
> Should I request their or you can directly assign?

I am directly assigning you.

**Comment by adarsh-singh01** [comment]
Hey, send something in #9 #85

**Comment by adarsh-singh01** [comment]
It only shows those people in assigning who have commented something in that PR or issue

**Comment by SamarthUrane** [comment]
Ok I will request their

**Comment by adarsh-singh01** [comment]
Send a message in That PR also.. So you both will be added as a contributor when that PR gets merged

**Comment by SamarthUrane** [comment]
Ok

**Comment by SamarthUrane** [comment]
Hey @adarsh-singh01 I haven't started working on history page yet. I think that other guy's implementation was pretty good. If you want some changes in that we can work on that later

**Comment by adarsh-singh01** [comment]
Are you on LinkedIn?

**Comment by adarsh-singh01** [comment]
> Hey @adarsh-singh01 I haven't started working on history page yet. I think that other guy's implementation was pretty good. If you want some changes in that we can work on that later

Okay.

**Comment by SamarthUrane** [comment]
> Are you on LinkedIn or X?

Actually I have sent you request but you haven't accepted it yet on LinkedIn

**Comment by adarsh-singh01** [comment]
> > Are you on LinkedIn or X?
> 
> Actually I have sent you request but you haven't accepted it yet on LinkedIn 

Accepted!... My LinkedIn notifs are off... So I didn't saw that.

**Comment by SamarthUrane** [comment]
Actually I am getting plain text as output from the API so it is difficult to format and show plain text on the page in more attractive way

**Comment by SamarthUrane** [comment]
To provide highly personalized recommendations, additional information for each family member would be required. 
For now, we can offer more generalized recommendations based on household data such as electricity and water usage, waste generation, and meal preferences. 
For more specific and tailored suggestions, we may need to collect additional details for each family member individually. 
This can be considered for future enhancements to ensure the recommendations are as accurate and personalized as possible.

**Comment by adarsh-singh01** [comment]
> To provide highly personalized recommendations, additional information for each family member would be required. For now, we can offer more generalized recommendations based on household data such as electricity and water usage, waste generation, and meal preferences. For more specific and tailored suggestions, we may need to collect additional details for each family member individually. This can be considered for future enhancements to ensure the recommendations are as accurate and personalized as possible.

what additional details do we need from each family member individually apart from transport and meal?

whose api are you using?...chatgpt?

**Comment by SamarthUrane** [comment]
I am using Gemini which is free. Chatgpt is paid.
We can generate recommendation using given data but I search some how to more personalize it then I got some other data that will help.

**Comment by SamarthUrane** [comment]
I don't think that kind of personalization is needed at this stage

**Comment by adarsh-singh01** [comment]
> I don't think that kind of personalization is needed at this stage

Okay
