### ISSUE TITLE
Enhance Website with a Video Background and Updated Footer

### ISSUE THREAD

**Issue by nirajsingh015** [adarsh-singh01/PrithWe#96]
![image](https://github.com/adarsh-singh01/PrithWe/assets/115022991/979f5ae0-05dd-4683-99f2-4b19ccc9bc23)
To create a more engaging and visually appealing website,Use the video as the  background video on the homepage with text overlay positioned at the top, middle, or bottom.
![image](https://github.com/adarsh-singh01/PrithWe/assets/115022991/05730e05-984b-4fbc-8430-7c5fb1d3d3fd)
Enhance the footer by including icons and links to your social media profiles. This provides easy access for users to connect with you on different platforms.
Benefits: Increases user engagement and extends your online presence.

As a part of my gssoc  contribution  i would like to do these.

**Comment by adarsh-singh01** [comment]
Send a demo... What kind of video

**Comment by nirajsingh015** [comment]
https://github.com/adarsh-singh01/PrithWe/assets/115022991/937a2b61-d191-458f-87f3-a9915994e735

hey @adarsh-singh01 this is the demo video
