### ISSUE TITLE
Feature: Added scroll up button to footer.

### ISSUE THREAD

**Issue by soniya-malviy** [adarsh-singh01/PrithWe#98]
Adding scroll up button in footer so that user can directly go up to top when clicked the button.
which provide better user experience and enhance website.

**Comment by adarsh-singh01** [comment]
> Adding scroll up button in footer so that user can directly go up to top when clicked the button.
> which provide better user experience and enhance website.

Hey Soniya, This issue is already assigned to another contributor... See if you can contribute in any bug or feature that is missing.

**Comment by adarsh-singh01** [comment]
Can you please give a star to this repo.
